# Generated by Django 6.0.4 on 2026-05-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('total_alumnos', models.IntegerField(blank=True, null=True)),
                ('total_docentes', models.IntegerField(blank=True, null=True)),
                ('ratio_alumno_docente', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['anio', 'provincia'],
                'unique_together': {('provincia', 'anio')},
            },
        ),
    ]
